### ISSUE TITLE
[Question] Log to a file and Stderr

### ISSUE THREAD

**Issue by maxibanki** [inconshreveable/log15#103]
Hello,
first of all, this is a great logger. But I have a question, about saving the log Output to a file and the Stderr. I have´t find out anything yet in the WWW.
Thank you,
~Max

**Comment by inconshreveable** [comment]
Try something like this:

```go
handler := log.MultiHandler(
    log.Must.FileHandler("/var/log/service.json", log.JsonFormat()),
    log.StderrHandler()
)
log.Root().SetHandler(handler)
```
