### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by vincentbernat** [inconshreveable/log15#104]
Hey!

It has been quite some time since the latest release (september 2015). When using the package through gopkg.in, we get tagged release only.

I am notably interested by the small change that did convert the level to its string representation when using the JSON format.

Thanks!

**Comment by iron-s** [comment]
There is another use-case for this as well - dep  tool (https://github.com/golang/dep) gives much higher preference to tags then to master branch. Details available here: https://github.com/golang/dep/blob/master/docs/FAQ.md#how-does-dep-decide-what-version-of-a-dependency-to-use

**Comment by kevinburke** [comment]
Just pushed v2.12. Sorry for the slowness here.
