### ISSUE TITLE
failed build on app engine

### ISSUE THREAD

**Issue by kevinburke** [inconshreveable/log15#123]
Reported failure here: https://github.com/kevinburke/rest/pull/4#issuecomment-277801954

I've been unable to reproduce it, because you can't specify `GOOS=appengine` and compile the build. Need to set up the App Engine SDK locally and test using that OS.

If I had to guess, I would guess that App Engine is not a subset of `linux` and so the terminal_notwindows.go file also compiles there.

**Comment by kevinburke** [comment]
cc @andrewwatson

**Comment by andrewwatson** [comment]
changed notwindows like so 
```
// +build linux,!appengine darwin,!appengine freebsd openbsd netbsd
``` 
without success

**Comment by andrewwatson** [comment]
removing notwindows completely didn't fix it either, though!

**Comment by andrewwatson** [comment]
aha! added // +build !appengine to darwin and it compiles / runs locally now

**Comment by kevinburke** [comment]
Interesting... I'd expect that if you are running Darwin locally. How about in production?

**Comment by andrewwatson** [comment]
well, i hadn't had a chance to deploy it to production since i added twilo-go which is how i got into this rabbit hole in the first place 😄
