### ISSUE TITLE
Writing field's address instead of it's value

### ISSUE THREAD

**Issue by goloveychuk** [inconshreveable/log15#127]
I have structure
```go
type MyStruct struct {
		Val  *string
		Val2 *string
}
s := "asd"
struc := MyStruct{Val: nil, Val2: &s}
logger.Info("struc", "struc", struc)
```
and have
```
INFO[02-27|15:02:44] struc module=scenarios struc="{Val:<nil> Val2:0xc4202eb440}"
``` 
in output. 
Have
```go
log.StreamHandler(colorable.NewColorableStdout(), log.TerminalFormat())
```
handler. 
Could you tell me if it's correct behaviour (due to performance reasons) or this is bug?

**Comment by kevinburke** [comment]
Hey, yes, I think that's the correct behavior. Here's the logic, I believe

```
	case string:
		return escapeString(v)
	default:
		return escapeString(fmt.Sprintf("%+v", value))
```

You can change it by modifying the object you send to log15, not sending a pointer, or defining a custom `String()` method which should get called first, I believe.
