### ISSUE TITLE
logfmt/json keys for msg/lvl/t are hard-coded

### ISSUE THREAD

**Issue by neilisaac** [inconshreveable/log15#147]
Some logging services (ex. LogDNA) only parse specific key names to parse the log level and message.  It would be nice if these were user configurable.

Proposed enhancement implemented in https://github.com/inconshreveable/log15/pull/145

**Comment by neilisaac** [comment]
Sounds like a good workaround, thanks @ChrisHines.  Is this preferable over an interface change in the library?

**Comment by ChrisHines** [comment]
Yes, changing the interface would be a breaking change.
