### ISSUE TITLE
Reintroduce syslog facility/severity support

### ISSUE THREAD

**Issue by sborsje** [inconshreveable/log15#37]
Currently it's not possible to configure which syslog facility the syslog handler will log from. This means that all logs will be logged from the "kern" facility, since this is the default within the stdlib syslog package. This is confusing, because "kern" should be used for kernel logging only.

I noticed that syslog priority configuration used to be supported in this library, but it was removed in commit 54d74c8. Could you maybe reintroduce this? If not, it might be a good idea to pick a better default.

**Comment by raphael** [comment]
I'm hitting that same issue - is there more to it than reverting that commit?

**Comment by inconshreveable** [comment]
Reverted 54d74c8372bb9351be6c9ca09bee11eeb2bcc37a
