### ISSUE TITLE
Compilation failure on app engine

### ISSUE THREAD

**Issue by karalabe** [inconshreveable/log15#40]
Currently compilation fails on app engine due to a missing term.IsTty method, since all term files have specific build tags that exclude appengine.

**Comment by karalabe** [comment]
Well, it seams there are a whole lot of issues with gae (disallowed imports: unsafe, syscall).

**Comment by karalabe** [comment]
I've opened a pull request with a fix: https://github.com/inconshreveable/log15/pull/41

**Comment by inconshreveable** [comment]
Fixed in #41
