### ISSUE TITLE
Hooks with external logging services (loggly)

### ISSUE THREAD

**Issue by GeertJohan** [inconshreveable/log15#42]
First of all, thanks for creating this great logging package. I've looked at all the popular packages out there and I definitly like this one best!

I've created a very simple Handler/hook that sends logs to loggly. It depends on `github.com/segmentio/go-loggly`. Do you think handlers like these should just have their own repository, or could we include them in this repository?

I think the package should at least have its own package to avoid downloading the go-loggly dependency when `go get`-ing log15. Maybe it could be something like `github.com/inconshreveable/log15/hooks/logglyhook`. Name it `logglyhook` to avoid naming conflict because the user also needs to be importing `go-loggly` to create the hook.

Here's a gist of how the code looks right now: https://gist.github.com/GeertJohan/6214d2e04957610235ad

Cheers!

**Comment by GeertJohan** [comment]
**instant update**: I've changed the code a bit, NewLogglyHook now takes the loggly token directly.
https://gist.github.com/GeertJohan/3d83e85f6e028dcea832

This means the package can be named `github.com/inconshreveable/log15/hooks/loggy` and users dont have to import `go-loggy` to setup the loggly client.

**Comment by GeertJohan** [comment]
Any update on this?

**Comment by ChrisHines** [comment]
@GeertJohan It would seem this issue falls under the umbrella of issue #5, which suggests it should go in the ext package, but I agree with you that the dependency on go-loggly should be isolated.

If we do accept this into the log15 repo I would vote for it to go in log15/ext/loggly.

**Comment by GeertJohan** [comment]
I'll provide a PR shortly.

**Comment by GeertJohan** [comment]
#44 is ready and can be merged.
