### ISSUE TITLE
Provide changelog & migration help

### ISSUE THREAD

**Issue by GeertJohan** [inconshreveable/log15#50]
In a relatively short period of time (may 2014) and only 87 comits, log15 is at v2 already.
In #34 it's mentioned that when it is merged, the version should be bumped to v3.

Maybe it's good to keep a document (e.g.: `CHANGELOG.md`) that contains the important changes and provides help with migration for breaking changes.

**Comment by ChrisHines** [comment]
I agree.

**Comment by inconshreveable** [comment]
I agree as well, this is a good idea.

**Comment by inconshreveable** [comment]
Added a breaking changes section to the README.
