### ISSUE TITLE
Adjust stack depth

### ISSUE THREAD

**Issue by grahamking** [inconshreveable/log15#59]
We're using log15 behind a wrapper, which means I'd like `runtime.Callers` to say `4`, instead of `3`:
https://github.com/inconshreveable/log15/blob/master/logger.go#L110

Is there a way around this? 

If not, would this be ok?

     log.Root().SetStackDepth(4)

It's a small change, but it adds a method to the `Logger` interface, which is a very nice clean interface.

**Comment by ChrisHines** [comment]
What does your wrapper do? Can it be achieved by a Handler instead?

**Comment by grahamking** [comment]
It provides an adapter from the `log4go` API. We're a big project, switching from that to log15. It means the bulk of our code can depend only on our internal log package.

**Comment by ChrisHines** [comment]
Adding a method to the `Logger` interface would require a new API version (log15.v3) and I agree it would be a shame if we were to clutter the interface for this reason.

It would probably be OK to add a package scoped variable (guarded by sync/atomic) with an exported `log15.SetStackDepth` function to modify it. If the sync/atomic is prohibative we could document that SetStackDepth must be called before any logging is performed.

**Comment by grahamking** [comment]
Some parts of our code will use log15 directly (structured logging!), and some through the wrapper (to keep older code working), so a package-level wouldn't work.

Having spent a bit more time with log15, I can do it with a handler like you suggested. The approach is the same as `CallerStackHandler`:
```
func addCaller(r *log15.Record) {
        callers := stack.Callers().TrimBelow(stack.Call(r.CallPC[0]))
        caller := fmt.Sprintf("%v", callers[0])
        if strings.HasPrefix(caller, "nlog.go") { // Trim this package
                caller = fmt.Sprintf("%v", callers[1])
        }
        r.Ctx = append(r.Ctx, "caller", caller)
}
```
The disadvantage is calling `runtime.Callers` again. If [Record.CallPC](https://github.com/inconshreveable/log15/blob/master/logger.go#L67) was a 2 array, I could use that. But that's an optimization, and I don't have any numbers, so I should be good for now. Thanks for your help!

**Comment by ChrisHines** [comment]
I'm glad you found a work around.

It's not ready for production yet, but you might want to keep an eye on the log package in https://github.com/go-kit/kit. Its design draws heavily from lessons learned with log15, and I think the way we implemented recording caller information in that package supports the use case you have described here. Disclaimer: I contribute to both log15 and Gokit.
