### ISSUE TITLE
Invalid yaml file in repo

### ISSUE THREAD

**Issue by rogierlommers** [inconshreveable/log15#62]
https://raw.githubusercontent.com/inconshreveable/log15/master/.travis.yml

This one is invalid. I have a yaml validator as a git hook in my project (which uses log15) and it complains after saving log15 with godep :). Can you please remove the tabs?

![screen shot 2015-08-13 at 14 43 25](https://cloud.githubusercontent.com/assets/3907131/9249954/b2aca3ec-41c9-11e5-852d-e0612ce7a79d.png)

**Comment by inconshreveable** [comment]
fixed! thanks for the report

**Comment by rogierlommers** [comment]
Thanks; can you also commit to the .v2 tag?
https://github.com/inconshreveable/log15/blob/v2/.travis.yml

**Comment by inconshreveable** [comment]
done!

**Comment by rogierlommers** [comment]
Appreciate it.
