### ISSUE TITLE
Shortcut logging for errors

### ISSUE THREAD

**Issue by abourget** [inconshreveable/log15#73]
In https://github.com/inconshreveable/log15/blob/1c1f55cde622aae2c80b2dce7342b8cb648e2103/logger.go#L152-L170 I see there is support for `args` being 1 argument, considered to be a `log.Ctx`, and pairs of arguments, to be keys and values.

I propose the support of an implicit "err" argument:
```
log.Error("woah something happened", err)
```
would see that `err` is of type `error`, and "prefix" it with the `"err"` key.

Something like:

```
if _, ok := args[0].(error); ok {
    args = prepend(args, "err")
}
```

(first ensuring there is at least 1 argument)

This would avoid those things I see often:

```
log.Error("there was an error", "err", err)
```

that's 4 times the word "err" in there!

**Comment by inconshreveable** [comment]
I sympathize with the redundancy, but I think this kind of special casing of the API would make it more confusing. The use of an even number of arguments for alternating key-value pairs is already pushing the limits of acceptability, adding special cases to it would add complexity for both the library and for developers puzzling over the exceptional behavior, which to my mind doesn't justify shortcutting a few extra characters in the logging code. Finally, it's easy enough for someone to create their own new logger object wrapper with an additional method that implements this behavior.
