### ISSUE TITLE
Double escaped output

### ISSUE THREAD

**Issue by davisford** [inconshreveable/log15#74]
How can I tweak things so this kind of thing:

```go
var body, err := ioutil.ReadAll(resp.Body) // http 
var bodyStr = string(body) // JSON posted back

log.Info("response", "body", bodtStr)
```

output:

```
INFO[03-11:12:16:26] response            body="{\r\n   \n"foo\": \"bar\" \r\n}"
```

I don't want all the [escaping](https://github.com/inconshreveable/log15/blob/master/format.go#L225) -- do I need to write my own formatter that bypasses this escaping?  

What if I want conditional escaping -- escaping on some fields but not others ...is there a path to achieve that?

**Comment by inconshreveable** [comment]
Escaping happens at the very ned with the `Formatter` runs. If you define your own custom `Handler` you can selectivity escape things in a way that you find more tasteful for your logs before that's done by the `Formatter`. Does that work?

**Comment by davisford** [comment]
Yea, I guess i need to spend a bit more time looking at how the handler + formatter hook up.  I can write my own formatter...as long as it's possible to plugin my own solution, should be fine.  thanks!

**Comment by inconshreveable** [comment]
It's possible to write your own formatter but rarely a good idea to. it's usually going to be much, much easier to write a `Handler`
