### ISSUE TITLE
Update documentation with new release policy and remove all uses of gopkg.in

### ISSUE THREAD

**Issue by moxar** [inconshreveable/log15#76]
Hi, 

Do you intend to release a new tag v2.xx soon ? The last one came in september, and there are some pretty feature that have been implemented since.

**Comment by inconshreveable** [comment]
The Go community has essentially decided that the vendor experiment is the way forward, so I think we'll just update all the docs to encourage folks to import `github.com/inconshreveable/ngrok` and vendor it appropriately.

**Comment by inconshreveable** [comment]
Fixed in 03f7e3c942fe248f8dd5f5ad5e714b57ef7e419a
