### ISSUE TITLE
tests fail when there is more than one path in $GOPATH

### ISSUE THREAD

**Issue by mwhudson** [inconshreveable/log15#77]
```
$ GOPATH=$GOPATH:/tmp /usr/bin/go test gopkg.in/inconshreveable/log15.v2/...
ok  	gopkg.in/inconshreveable/log15.v2	0.091s
ok  	gopkg.in/inconshreveable/log15.v2/ext	0.041s
--- FAIL: TestCallFormat (0.00s)
	stack_test.go:80: fmt.Sprintf("%+s", Call(func)) = gopkg.in/inconshreveable/log15.v2/stack/stack_test.go, want ../../../gopath/src/gopkg.in/inconshreveable/log15.v2/stack/stack_test.go
	stack_test.go:80: fmt.Sprintf("%+v", Call(func)) = gopkg.in/inconshreveable/log15.v2/stack/stack_test.go:24, want ../../../gopath/src/gopkg.in/inconshreveable/log15.v2/stack/stack_test.go:24
	stack_test.go:80: fmt.Sprintf("%+s", Call(meth)) = gopkg.in/inconshreveable/log15.v2/stack/stack_test.go, want ../../../gopath/src/gopkg.in/inconshreveable/log15.v2/stack/stack_test.go
	stack_test.go:80: fmt.Sprintf("%+v", Call(meth)) = gopkg.in/inconshreveable/log15.v2/stack/stack_test.go:18, want ../../../gopath/src/gopkg.in/inconshreveable/log15.v2/stack/stack_test.go:18
FAIL
FAIL	gopkg.in/inconshreveable/log15.v2/stack	0.002s
?   	gopkg.in/inconshreveable/log15.v2/term	[no test files]
```

**Comment by inconshreveable** [comment]
gross :( @ChrisHines should we update to use `stack.v1`?

**Comment by mwhudson** [comment]
I'm about to send a PR with a simple fix

**Comment by ChrisHines** [comment]
@inconshreveable Yes, I think we should switch, github.com/go-stack/stack has a better implementation.

**Comment by ChrisHines** [comment]
I will submit a separate PR for the switch and we can evaluate from there.

**Comment by ChrisHines** [comment]
Well, maybe not. Switching to `github.com/go-stack/stack` would require changing the type of field `log15.Record.CallPC` to `go-stack/stack.Call`. That would be a breaking API change since the `CallPC` field is exported. The other alternative is to add add a constructor for type `go-stack/stack.Call` that accepts an arbitrary PC value, but I don't really like that idea.

@inconshreveable Thoughts?

**Comment by inconshreveable** [comment]
it seems the Go community has settled on constant API breakage and vendoring, so i think it's time we started breaking APIs to make the library better and we'll just document the changes

**Comment by ChrisHines** [comment]
@inconshreveable I am fine with that philosophy. What about use of gopkg.in? I have stopped recommending its use with my packages. There has been some push back from some users. They don't want to rely on gopkg.in or similar proxy servers.

If we're going to break the API that would imply a v3. Clearly we would tag the repo appropriately and it would still work via gopkg.in, but do you want to keep that the official import path? I do not have a strong opinion either way.

**Comment by inconshreveable** [comment]
yep, i think it's time to drop gopkg.in as official in the documentation given that vendoring is what the community has decided on.

**Comment by ChrisHines** [comment]
OK. I will submit a PR to switch from log15/stack to github.com/go-stack/stack and update the docs affected by that change. I will leave updating the docs to switch away from gopkg.in as a separate exercise.

**Comment by inconshreveable** [comment]
Yep, sounds good. I'll take care of that.

**Comment by ChrisHines** [comment]
@mwhudson I have verified that the tests in github.com/go-stack/stack work correctly when $GOPATH has multiple paths.

**Comment by ChrisHines** [comment]
Fixed by #79.

**Comment by mwhudson** [comment]
Given that I found this in a distro context, I'm not super wild about the embracing of vendoring, but thanks for fixing the problem!

**Comment by inconshreveable** [comment]
a distro context? can you elaborate?

**Comment by nbraud** [comment]
@inconshreveable @mwhudson is part of the Debian [pkg-go team](https://pkg-go.alioth.debian.org)

**Comment by inconshreveable** [comment]
Fascinating, I hadn't realized debian was packaging go libraries now, thanks!

**Comment by ChrisHines** [comment]
@inconshreveable I hope we continue to use good semver style release tags on log15.
