### ISSUE TITLE
invalid formatting directive

### ISSUE THREAD

**Issue by kevinburke** [inconshreveable/log15#96]
`go vet ./...` warns:

```
handler.go:109: unrecognized printf verb 'n'
```

This is the line in question:

```go
r.Ctx = append(r.Ctx, "fn", fmt.Sprintf("%+n", r.Call))
```

This commit has been around since 2014 at least. The fmt docs don't mention `%n` or `%+n`: https://golang.org/pkg/fmt/

I tried switching to `%+s`, `%+v`, `%#v`, but these all made the tests fail/changed the output, so I'm uncertain what rule Go is applying for that directive, or how to fix it.

**Comment by ChrisHines** [comment]
Look at the docs for github.com/go-stack/stack.

**Comment by ChrisHines** [comment]
Also, go vet isn't perfect.

**Comment by kevinburke** [comment]
Yeah, it's the only thing warning in my application though. FWIW I tried calling `Format()` directly but it's not easy to construct a `fmt.State` manually. :(

**Comment by inconshreveable** [comment]
Yep, not a bug. Basically, you can define the `Formatter` interface and define your own custom formatting directives like `%+#z`. `go-stack` does exactly that and `go vet` like Chris said is not intelligent enough to understand that's possible. i'm not sure if `go vet` accepts comments to suppress warnings, but that might be a decent solution to this problem
